Milestone 2: Math magicans(tests)
Gardimy/Math-magicians pull request #7
Opened 2023-06-15 20:46 UTC by Gardimy

**For this milestone, I write unit tests for the Math Magicians app, using the Jest and React Testing Library Libraries.**

2023-06-15 21:55 UTC, AmaduKamara reviewed
# Status: Invalid Submission ❌ ❌ ❌

Hi @Gardimy,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not follow the proper requirements as expected:

- [ ] It is required that every member contribute to this project and commit history will be checked to see if everyone contributes. Only one person made commits to this project.
- [ ] Kindly have your team member participate in this project or if there is a proof of absence or allowed to work solo by student success, kindly attach reference in your PR. 👍🏽

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._
```

2023-06-16 16:00 UTC, ShadyShawkat requested changes
## Hi @Gardimy, 

Good job so far! 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight
- All linters are passing ✔️ 
- Correct use of GitFlow ✔️ 
- Descriptive commit messages ✔️ 
- Professional looking pull request ✔️ 

![Image](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-16 16:00 UTC, ShadyShawkat commented on src/test/operate.test.js
> +
- [ ] Please make sure to implement more integration tests for user interactions, as per [this](https://github.com/microverseinc/curriculum-react-redux/blob/main/math-magicians/project_tests.md#:~:text=Use%20React%20Testing%20Library%20to%20simulate%20user%20interaction.) requirement.

2023-06-16 17:52 UTC, jerryowusu approved these changes
Hi Team

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![chelsea-mason-approve](https://github.com/Gardimy/Math-magicians/assets/65233860/354eb7be-1ed3-467d-8c46-52e2a0ee4499)


## Highlights
All tests passed :+1: 
Great effort in making the requested changes :+1: 

## Optional suggestions

- [ ] Nice work so far. However, you were suppose to write unit tests for all the components  as part of the project requirements. I am making it optional because the previous reviewer did not stress on that, but I would strongly advise you to work on that before moving to the next milestone. :pray: 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-16 19:29 UTC, merged